### ISSUE TITLE
Not able to use templateUrl in app.component.ts file

### ISSUE THREAD

**Issue by sirius93** [gonzofish/semaphore-ng2-webpack#5]
Hi guys, I am not able to use templateUrl in my *.component.ts files and i need to use template:require('') instead of it. can you please guide me what changes do i need to make into my file structure or in webpac configuration. TIA

**Comment by gonzofish** [comment]
There is a Webpack loader that allows you to use `templateUrl` and `styleUrls` without `require`: [angular2-template-loader](https://github.com/TheLarkInn/angular2-template-loader). This hasn't been updated in the tutorials because the tutorial were trying to stay consistent with each other and the tutorials were developed before `angular2-template-loader` was well-known.

Basically in the webpack configs you just add a second [loader for TS files](https://github.com/gonzofish/semaphore-ng2-webpack/blob/master/webpack/webpack.dev.js#L24) that pipes through `angular2-template-loader`. So the line in the previous link would go from:

```javascript
            { exclude: /node_modules/, loader: 'ts', test: /\.ts$/ }
```

to

```javascript
            { exclude: /node_modules/, loaders: ['ts', 'angular2-template'], test: /\.ts$/ }
```

I haven't tested it with this setup, but I'm using it in other projects. Hope this helps!

Note: I would suggest sticking with version `"0.6.0"` (no `^` or `~` prefix) because I've noticed some issues with 0.6.1 & 0.6.2.

**Comment by sirius93** [comment]
Hi,
It worked like charm :) Thank you for the help

**Comment by gonzofish** [comment]
No problem!
