### ISSUE TITLE
Can you please help me to configure webpack running unit test cases for Angular 4 ,Karma and Jasmine.

### ISSUE THREAD

**Issue by vittal288** [gonzofish/semaphore-ng2-webpack#7]

**Comment by gonzofish** [comment]
It's not something I can easily do here since the set up is like an article all on its own--I recommend looking at libraries that set up projects for you, such as [Angular Starter](https://github.com/AngularClass/angular-starter) from Angular Class

Like this library the important files for setup are `tsconfig.*.json`, `webpack.*.js`, and `karma.conf.json`, as well as the packages installed via `package.json`
